document.write("<footer class=\"footer\">");
      document.write("<div class=\"container\">");
        document.write("<div class=\"row\">");
          document.write("<div class=\"col-lg-5 col-sm-5 address wow fadeInUp\" data-wow-duration=\"2s\" data-wow-delay=\".1s\">");
            document.write("<h1>contact info");
            document.write("</h1>");
            document.write("<address>");
              document.write("<p>");
              	document.write("<i class=\"fa fa-home pr-10\">");
              	document.write("</i>Address: #14, AJR Pride, 2nd Floor, 27th Main, Sector 1,HSR Layout, Bangalore-560102");
              document.write("</p>");
              document.write("<p>");
              	document.write("<i class=\"fa fa-globe pr-10\">");
              	document.write("</i>Karnataka, India ");
              document.write("</p>");
              document.write("<p>");
              	document.write("<i class=\"fa fa-mobile pr-10\">");
              	document.write("</i>Mobile : +91-9008659007"); 
              document.write("</p>");
             
              document.write("<p>");
              	document.write("<i class=\"fa fa-envelope pr-10\">");
              	document.write("</i>Email :   info@saytrees.org");
              document.write("</p>");
            document.write("</address>");
          document.write("</div>");
          document.write("<div class=\"col-lg-1 col-sm-1 wow fadeInUp\" data-wow-duration=\"2s\" data-wow-delay=\".3s\">&nbsp;");
          document.write("</div>");
          document.write("<div class=\"col-lg-3 col-sm-3\">");
            document.write("<div class=\"page-footer wow fadeInUp\" data-wow-duration=\"2s\" data-wow-delay=\".5s\">");
              document.write("<h1>SAYTREES");
              document.write("</h1>");
              document.write("<ul class=\"page-footer-list\">");
                document.write("<li>");
                  document.write("<i class=\"fa fa-angle-right\">");
                  document.write("</i>");
                  document.write("<a href=\"http://www.saytrees.org/AboutUs.html\">About Us");
                  document.write("</a>");
                document.write("</li>");
                document.write("<li>");
                  document.write("<i class=\"fa fa-angle-right\">");
                  document.write("</i>");
                  document.write("<a href=\"http://www.saytrees.org/Contact.php\">Contact Us");
                  document.write("</a>");
                document.write("</li>");
                document.write("<li>");
                  document.write("<i class=\"fa fa-angle-right\">");
                  document.write("</i>");
                  document.write("<a href=\"http://www.saytrees.org/Volunteer.html\">Volunteer");
                  document.write("</a>");
                document.write("</li>");
                document.write("<li>");
                  document.write("<i class=\"fa fa-angle-right\">");
                  document.write("</i>");
                  document.write("<a href=\"http://www.saytrees.org/Donate.php\">Donate");
                  document.write("</a>");
                document.write("</li>");
              document.write("</ul>");
            document.write("</div>");
          document.write("</div>");
          document.write("<div class=\"col-lg-3 col-sm-3\">");
            document.write("<div class=\"text-footer wow fadeInUp\" data-wow-duration=\"2s\" data-wow-delay=\".7s\">");
              document.write("<h1>Save Trees");
              document.write("</h1>");
              document.write("<p>The best time to plant a sapling was 20 years ago. The next best time is now. - Chinese proverbs.");
              document.write("</p>");
              document.write("<br><p>Logistics Partner<br>");
              document.write("<a href=\"http://www.blowhorn.net\" target=\"_blank\"><img src=\"http://www.saytrees.org/images/blowhornLogo.png\"/></a>");
              document.write("</p>");
            document.write("</div>");
          document.write("</div>");
        document.write("</div>");
      document.write("</div>");
    document.write("</footer>");
    document.write("<footer class=\"footer-small\">");
        document.write("<div class=\"container\">");
            document.write("<div class=\"row\">");
                document.write("<div class=\"col-lg-6 col-sm-6 pull-right\">");
                    document.write("<ul class=\"social-link-footer list-unstyled\">");
                        document.write("<li class=\"wow flipInX\" data-wow-duration=\"2s\" data-wow-delay=\".1s\">");
                        	document.write("<a href=\"https://www.facebook.com/SayTrees\" target=\"_blank\">");
                        		document.write("<i class=\"fa fa-facebook\">");
                        		document.write("</i>");
                        	document.write("</a>");
                        document.write("</li>");
                        document.write("<li class=\"wow flipInX\" data-wow-duration=\"2s\" data-wow-delay=\".5s\">");
                        	document.write("<a href=\"#\">");
                        		document.write("<i class=\"fa fa-twitter\">");
                        		document.write("</i>");
                        	document.write("</a>");
                        document.write("</li>");
                        document.write("<li class=\"wow flipInX\" data-wow-duration=\"2s\" data-wow-delay=\".8s\">");
                        	document.write("<a href=\"#\">");
                        		document.write("<i class=\"fa fa-youtube\">");
                        		document.write("</i>");
                        	document.write("</a>");
                        document.write("</li>");
                    document.write("</ul>");
                document.write("</div>");
                document.write("<div class=\"col-md-4\">");
                  document.write("<div class=\"copyright\">");
                  document.write("</div>");
                document.write("</div>");
            document.write("</div>");
        document.write("</div>");
    document.write("</footer>");