document.write("<div class=\"head-section\">");
		document.write("<div class=\"navbar navbar-default navbar-static-top container\">");
				document.write("<div class=\"navbar-header\">");
						document.write("<button class=\"navbar-toggle\" data-target=\".navbar-collapse\" data-toggle=\"collapse\" type=\"button\">");
								document.write("<span class=\"icon-bar\"></span>");
								document.write("<span class=\"icon-bar\"></span>");
								document.write("<span class=\"icon-bar\"></span>");
						document.write("</button>");
						document.write("<a class=\"navbar-brand\" href=\"http://www.saytrees.org/index.html\"><img src=\"http://www.saytrees.org/images/logo.png\" /></a>");
				document.write("</div>");
				document.write("<div class=\"navbar-collapse collapse\">");
						document.write("<ul class=\"nav navbar-nav\">");
								document.write("<li>");
										document.write("<a href=\"http://www.saytrees.org/index.html\">Home</a>");
								document.write("</li>");
								document.write("<li>");
										document.write("<a href=\"http://www.saytrees.org/AboutUs.html\">About Us</a>");
								document.write("</li>");
								document.write("<li>");
										document.write("<a href=\"http://www.saytrees.org/Volunteer.html\">Volunteer</a>");
								document.write("</li>");
								document.write("<li>");
										document.write("<a href=\"http://www.saytrees.org/Corporates.html\">Corporates</a>");
								document.write("</li>");
								document.write("<li class=\"dropdown\">");
										document.write("<a class=\"dropdown-toggle\" data-close-others=\"false\" data-delay=\"0\" data-hover=\"dropdown\" data-toggle=\"dropdown\" href=\"#\">Plantations <i class=\"fa fa-angle-down\"></i></a>");
										document.write("<ul class=\"dropdown-menu\">");
												document.write("<li>");
														document.write("<a href=\"http://www.saytrees.org/Plantation2016.html\">In year 2016</a>");
												document.write("</li>");
												document.write("<li>");
														document.write("<a href=\"http://www.saytrees.org/Plantation2015.html\">In year 2015</a>");
												document.write("</li>");
												document.write("<li>");
														document.write("<a href=\"http://www.saytrees.org/Plantation2014.html\">In year 2014</a>");
												document.write("</li>");
												document.write("<li>");
														document.write("<a href=\"http://www.saytrees.org/Plantation2013.html\">In year 2013</a>");
												document.write("</li>");
												document.write("<li>");
														document.write("<a href=\"http://www.saytrees.org/Plantation2012.html\">In year 2012</a>");
												document.write("</li>");
												document.write("<li>");
													document.write("<a href=\"http://www.saytrees.org/Plantation2011.html\">In year 2011</a>");
												document.write("</li>");
												document.write("<li>");
													document.write("<a href=\"http://www.saytrees.org/Plantation2010.html\">In year 2010</a>");
												document.write("</li>");
												document.write("<li>");
													document.write("<a href=\"http://www.saytrees.org/Plantation2008.html\">In year 2008</a>");
												document.write("</li>");
										document.write("</ul>");
								document.write("</li>");
								document.write("<li>");
									document.write("<a href=\"http://www.saytrees.org/Donate.php\">Donate</a>");
								document.write("</li>");
										
								
								document.write("<li class=\"dropdown\">");
								document.write("<a class=\"dropdown-toggle\" data-close-others=\"false\" data-delay=\"0\" data-hover=\"dropdown\" data-toggle=\"dropdown\" href=\"#\">Media <i class=\"fa fa-angle-down\"></i></a>");
								document.write("<ul class=\"dropdown-menu\">");
										document.write("<li>");
												document.write("<a href=\"http://www.saytrees.org/Media.html\">Print Media</a>");
										document.write("</li>");
										document.write("<li>");
											document.write("<a href=\"http://www.saytrees.org/Video.html\">Videos</a>");
										document.write("</li>");
								document.write("</ul>");
								document.write("</li>");
								
								
								
								document.write("<li>");
										document.write("<a href=\"http://www.saytrees.org/Contact.php\">Contact</a>");
								document.write("</li>");
						document.write("</ul>");
				document.write("</div>");
		document.write("</div>");
document.write("</div>");